CREATE TABLE UMBOKDONG ( 
    UMBOKDONG STRING PRIMARY KEY CHECK ( UMBOKDONG = '엄복동' ) 
);

INSERT INTO UMBOKDONG VALUES ("엄복동");

-- INSERT INTO UMBOKDONG VALUES ("엄복동"); 
-- Error: UNIQUE constraint failed: UMBOKDONG.UMBOKDONG

-- INSERT INTO UMBOKDONG VALUES ("정지훈");
-- Error: CHECK constraint failed: UMBOKDONG
